name: freelancer_app
description: A new Flutter project.
publish_to: "none" 
version: 1.7.3+20

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.0.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  device_info_plus: ^10.1.0
  flutter_easyloading: ^3.0.5
  image_picker: ^1.1.2
  cached_network_image: ^3.2.0
  validators: ^3.0.0
  google_maps_flutter: ^2.7.0
  country_picker: ^2.0.19
  geolocator: ^12.0.0
  animated_bottom_navigation_bar: ^1.1.0+1
  flutter_svg:
  auto_size_text: ^3.0.0
  expandable: ^5.0.1
  sliding_up_panel: ^2.0.0+1
  intl: ^0.19.0
  google_place_plus: ^1.0.0
  google_directions_api: ^0.10.0
  flutter_polyline_points: ^2.0.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.8
  flutter_screenutil: ^5.6.1
  path_provider: ^2.0.15
  smooth_page_indicator: ^1.1.0
  calendar_date_picker2: ^1.1.4
  mobile_scanner: ^5.1.1
  pin_code_fields: ^8.0.1
  linear_progress_bar: ^1.1.0
  lottie: ^3.0.0
  razorpay_flutter: ^1.3.4
  uuid: ^4.4.0
  flutter_compass: ^0.8.1
  timeago:
  flutter_local_notifications: ^19.0.0
  share_plus: ^10.1.4
  web_socket_channel: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.3
  open_filex: ^4.7.0

  #firebase
  # google_sign_in: ^6.2.1
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  flutter_native_splash: ^2.3.1
  logger: ^2.0.2+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/emojis/
    - assets/lotty/
    - assets/

  fonts:
    - family: Sans Serif Shaded
      fonts:
        - asset: assets/fonts/SansSerifShaded.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family:  NavBarIcon
      fonts:
        - asset: assets/fonts/NavBarIcon.ttf  

